### ISSUE TITLE
TypeError: reqDomain.dispose is not a function

### ISSUE THREAD

**Issue by aDu** [baryshev/connect-domain#19]
Running on localhost, connect-domain v0.5.

```
/Users/alandu/web-projects/ft/web/node_modules/connect-domain/lib/connect-domain.js:17
			reqDomain.dispose();
			          ^

TypeError: reqDomain.dispose is not a function
    at Domain.<anonymous> (/Users/alandu/web-projects/ft/web/node_modules/connect-domain/lib/connect-domain.js:17:14)
    at Domain.emit (events.js:315:20)
    at Domain.EventEmitter.emit (domain.js:485:12)
    at Domain._errorHandler (domain.js:253:23)
    at Object.<anonymous> (domain.js:156:29)
    at process._fatalException (internal/process/execution.js:164:29)
```

**Comment by fholzer** [comment]
Nodejs deprecated `domain.dispose()` some time ago, breaking this package. See https://github.com/nodejs/node-v0.x-archive/commit/d86814aeca64d8985402dc073eff1fc8ac93c231

**Comment by webbrain-one** [comment]
Hi! I opened #22 to fix this. It replaces the invalid `reqDomain.dispose()` call with the proper domain cleanup, so the request domain is exited correctly instead of throwing `TypeError`.
